# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  print_name:
    docker:
      - image: cimg/node:lts
    steps:
      - run: echo $SWD_NAME
workflows:
  welcome:
    jobs:
      - print_name
