# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: cimg/node:lts
    steps:
      - run: |
          mkdir -p /tmp/workspace
          echo "Hello, world! I have been saved to a shared workspace." > /tmp/workspace/output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/node:lts
    steps:
      - run: cat /tmp/workspace/output.txt
      - attach_workspace:
          at: /tmp/workspace
workflows:
  welcome:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
