# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
  analyze:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-packages-{{ checksum "package-lock.json" }}
      - run: npm audit

workflows:
  default:
    jobs:
      - build
      - analyze:
          requires:
            - build
