export const displayNames = {
  'AE' : { fullName: 'Aeronautics', shortName: 'Aeronautics' },
  'AS' : { fullName: 'Agricultural Sciences', shortName: 'AS' },
  'BE' : { fullName: 'Bioengineering', shortName: 'Bioengineering' },
  'BS' : { fullName: 'Imperial College Business School', shortName: 'Business School' },
  'CE' : { fullName: 'Chemical Engineering & Chemical Technology', midName: 'Chemical Engineering', shortName: 'Chem Eng' },
  'CEX' : { fullName: 'Chemical Engineering and Chemical Technology', shortName: 'CEX' },
  'CfAE' : { fullName: 'Academic English', shortName: 'Acad. English'},
  'CH' : { fullName: 'Chemistry', shortName: 'Chemistry' },
  'CHX' : { fullName: 'Chemistry', shortName: 'CHX' },
  'CI' : { fullName: 'Civil & Environmental Engineering', midName: 'Civil Engineering', shortName: 'Civ Eng' },
  'CLCC' : { fullName: 'Centre for Languages, Culture, and Communication', midName: 'Langs, Culture & Comms', shortName: 'Lang, Cult & Comms' },
  'CO' : { fullName: 'Computing', shortName: 'Computing' },
  'CP' : { fullName: 'Centre for Co-Curricular Studies', midName: 'Co-Curricular Studies', shortName: 'Co-Curricular' },
  'CQ' : { fullName: 'Centre for Higher Education Research and Scholarship', midName: 'HE Research', shortName: 'HE Research' },
  'DA' : { fullName: 'School of Medicine', shortName: 'Medicine' },
  'DBIO' : { fullName: 'Division of Biology', midName: 'Division of Biology', shortName: 'Div Biology' },
  'DBIOX' : { fullName: 'Division of Biology', shortName: 'DBIOX' },
  'DC' : { fullName: 'Clinical Sciences Centre', midName: 'Clinical Sciences', shortName: 'Clinical Sci' },
  'DCMB' : { fullName: 'Division of Cell and Molecular Biology (PG)', midName: 'Div C&M Biology', shortName: 'Div C&M Bio' },
  'DCMBX' : { fullName: 'Division of Cell and Molecular Biology', shortName: 'DCMBX' },
  'DD' : { fullName: 'Division of Investigative Science', midName: 'Div Investigative Sci', shortName: 'Div Inv Sci' },
  'DE' : { fullName: 'Division of Epidemiology, Public Health & Primary Care', shortName: 'Div E, PH & PC' },
  'DLS' : { fullName: 'Life Sciences', shortName: 'Life Sciences' },
  'DM' : { fullName: 'Division of Medicine (PG)', midName: 'Div Medicine (PG)', shortName: 'Div Medicine' },
  'DMB' : { fullName: 'Division of Molecular Biosciences (PG)', midName: 'Div Molec Biosciences', shortName: 'Div Mol Bio' },
  'DQ' : { fullName: 'Faculty of Medicine (Summer School)', shortName: 'FoM Summer School' },
  'DSDE' : { fullName: 'Dyson School of Design Engineering', midName: 'Design Engineering', shortName: 'Design Eng' },
  'EA' : { fullName: 'Earth Science and Engineering', midName: 'Earth Science Eng', shortName: 'Earth Sci' },
  'EE' : { fullName: 'Electrical & Electronic Engineering', shortName: 'Elec Eng' },
  'EP' : { fullName: 'Centre for Environmental Policy', midName: 'Centre Enviro Policy', shortName: 'Enviro Policy' },
  'EPX' : { fullName: 'Centre for Environmental Policy', shortName: 'EPX' },
  'EQ' : { fullName: 'Centre for Educational Development', midName: 'Educational Development', shortName: 'Educational Dev' },
  'FC' : { fullName: 'Crick Doctoral Centre', midName: 'Crick Doctoral Centre', shortName: 'Crick' },
  'HO' : { fullName: 'Centre for the History of Science, Technology & Medicine', shortName: 'HO' },
  'HU' : { fullName: 'Humanities Programme', shortName: 'HU' },
  'HUM' : { fullName: 'Humanities', shortName: 'HUM' },
  'IC' : { fullName: 'Sabbatical Officers', shortName: 'Sabbs' },
  'ICBS' : { fullName: 'Imperial College Business School', shortName: 'Business School' },
  'INSPIRE' : { fullName: 'INSPIRE', shortName: 'INSPIRE' },
  'MA' : { fullName: 'Mathematics', shortName: 'Mathematics' },
  'MAX' : { fullName: 'Mathematics', shortName: 'MAX' },
  'ME' : { fullName: 'Mechanical Engineering', midName: 'Mechanical Engineering', shortName: 'Mech Eng' },
  'MM' : { fullName: 'Materials', shortName: 'Materials' },
  'MS' : { fullName: 'Tanaka Business School', shortName: 'MS' },
  'NM' : { fullName: 'Neuroscience and Mental Health', midName: 'Neuro & Mental Health', shortName: 'Neuro & MH' },
  'OT' : { fullName: 'Officer Trustees', midName: 'Officer Trustees', shortName: 'Off Trustees' },
  'OTSA' : { fullName: 'Officer Trustees & Sabbatical Officers', midName: 'Off Trustees & Sabbs', shortName: 'OTs & Sabbs' },
  'PH' : { fullName: 'Physics', shortName: 'Physics' },
  'PHX' : { fullName: 'Physics', shortName: 'PHX' },
  'SM' : { fullName: 'School of Medicine (UG)', shortName: 'Medicine (UG)' },
  'SR' : { fullName: 'Cross Departmental', shortName: 'Cross' },
  'UROP' : { fullName: 'Undergraduate Research Opportunities Program', shortName: 'UROP' },
  'WB' : { fullName: 'Brain Sciences', midName: 'Brain Sciences', shortName: 'Brain Sci' },
  'WC' : { fullName: 'Institute of Clinical Science', midName: 'Inst Clinical Science', shortName: 'Clinical Sci' },
  'WD' : { fullName: 'Infectious Diseases', midName: 'Infectious Diseases', shortName: 'Infect Dis' },
  'WH' : { fullName: 'National Heart and Lung Institute', shortName: 'NHLI' },
  'WI' : { fullName: 'Immunology and Inflammation', midName: 'Immunology & Inflam.', shortName: 'Immunology' },
  'WM' : { fullName: 'Medicine (Other PG)', shortName: 'Medicine (Other PG)' },
  'WP' : { fullName: 'School of Public Health', midName: 'School of Public Health', shortName: 'Public Health' },
  'WR' : { fullName: 'Metabolism, Digestion, and Reproduction', midName: 'Metab, Digest & Repro', shortName: 'Metabolism' },
  'WS' : { fullName: 'Surgery and Cancer', midName: 'Surgery and Cancer', shortName: 'Surg & Can' },
  // Dev only
  'AW' : { fullName: 'Awesomeness', shortName: 'Awesomeness' },
  'BB' : { fullName: 'Beards', shortName: 'Beards' },
  'CT' : { fullName: 'Chat', shortName: 'Chat' },
}
