export const displayNames = {
  'Alban' : { fullName: 'Alban Hall', shortName: 'Alban Hall' },
  'Beit' : { fullName: 'Beit Hall', shortName: 'Beit Hall' },
  'Bernard Sunley' : { fullName: 'Bernard Sunley Hall (Evelyn Gardens)', shortName: 'Bernard Sunley' },
  'Bernard Sunley & Southwell' : { fullName: 'Southwell and Bernard Sunley Hall (Evelyn Gardens)', shortName: 'Southwell & BS' },
  'Boat House' : { fullName: 'Boat House', shortName: 'Boat House' },
  'Chapter Islington (Paragon)' : { fullName: 'Chapter Islington (Paragon)', shortName: 'Islington' },
  'Falmouth & Keogh' : { fullName: 'Falmouth Hall & Keogh Hall (Southside West)', midName: 'Falmouth & Keogh', shortName: 'Fal & Keogh' },
  'Fisher' : { fullName: 'Fisher Hall (Evelyn Gardens)', shortName: 'Fisher' },
  'Gabor' : { fullName: 'Gabor Hall (Eastside Central)', shortName: 'Gabor' },
  'Griffon Studios' : { fullName: 'Griffon Studios', shortName: 'Griffon' },
  'Holbein & Willis Jackson' : { fullName: 'Holbein & Willis Jackson Hall (Evelyn Gardens)', shortName: 'Holbein & WJ' },
  'Linstead' : { fullName: 'Linstead Hall (Eastside South)', shortName: 'Linstead' },
  'Kemp Porter' : { fullName: 'Kemp Porter', shortName: 'Kemp Porter' },
  'Orient House' : { fullName: 'Orient House', shortName: 'Orient' },
  'Parsons' : { fullName: 'Parsons Hall', shortName: 'Parsons' },
  'Pembridge' : { fullName: 'Pembridge Hall', shortName: 'Pembridge' },
  'Pembridge & Parsons' : { fullName: 'Pembridge, Parsons & Alban', shortName: 'Pemb & Pars' },
  'Selkirk' : { fullName: 'Selkirk Hall (Southside East)', shortName: 'Selkirk' },
  'Silwood Halls' : { fullName: 'Silwood Halls (Residences)', shortName: 'Silwood' },
  'Southwell' : { fullName: 'Southwell Hall (Evelyn Gardens)', shortName: 'Southwell' },
  'Tizard' : { fullName: 'Tizard Hall (Southside Central)', shortName: 'Tizard' },
  'Wilkinson' : { fullName: 'Wilkinson (Eastside North) ', shortName: 'Wilkinson' },
  'Wilkinson & Weeks' : { fullName: 'Wilkinson & Weeks (Eastside North & Northside) ', shortName: 'Wilk & Weeks' },
  'Wilson House' : { fullName: 'Wilson House', shortName: 'Wilson' },
  'Wood Lane Studios' : { fullName: 'Wood Lane Studios', shortName: 'Wood Lane' },
  'Woodward Hall' : { fullName: 'Woodward Hall', shortName: 'Woodward' },
  'Xenia' : { fullName: 'Xenia', shortName: 'Xenia' }
}
